services:
  weather-service:
    build: .
    container_name: weather-service
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - portfolio-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./grafana-cloud-token.txt:/etc/prometheus/grafana-cloud-token.txt:ro
      - prometheus-data:/prometheus
    depends_on:
      - weather-service
    restart: unless-stopped
    networks:
      - default

volumes:
  prometheus-data:

networks:
  default: {}
  portfolio-network:
    external: true
    name: portfolio-network
